# Conda环境配置 
# environment.yml - Conda environment configuration for Enhanced InterPLM

name: enhanced-interplm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python version
  - python=3.9
  
  # Core scientific computing
  - numpy=1.24.*
  - scipy=1.11.*
  - pandas=2.0.*
  - scikit-learn=1.3.*
  
  # Deep learning
  - pytorch=2.1.*
  - torchvision=0.16.*
  - pytorch-cuda=11.8  # Adjust based on your CUDA version
  - cudatoolkit=11.8
  
  # Bioinformatics
  - biopython=1.81
  - hmmer=3.3.*
  - clustal-omega=1.2.*
  - muscle=5.1.*
  
  # Visualization
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - plotly=5.15.*
  
  # Data handling
  - h5py=3.9.*
  - zarr=2.16.*
  - pyarrow=13.0.*
  
  # Network analysis
  - networkx=3.1
  - graph-tool=2.45  # Optional, for advanced graph algorithms
  
  # Development tools
  - jupyter=1.0.*
  - ipywidgets=8.1.*
  - tqdm=4.66.*
  
  # Code quality
  - pytest=7.4.*
  - pytest-cov=4.1.*
  - black=23.9.*
  - flake8=6.1.*
  - mypy=1.5.*
  
  # Documentation
  - sphinx=7.2.*
  - sphinx_rtd_theme=1.3.*
  
  # System utilities
  - psutil=5.9.*
  - gputil=1.4.*
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
      # Transformers and ESM
      - transformers>=4.35.0
      - fair-esm>=2.0.0
      
      # Additional bio tools
      - biotite>=0.37.0
      - py3Dmol>=2.0.0
      
      # ML utilities
      - einops>=0.7.0
      - captum>=0.6.0  # For model interpretability
      - opt-einsum>=3.3.0
      
      # Experiment tracking
      - wandb>=0.15.0
      - tensorboard>=2.14.0
      - mlflow>=2.7.0  # Alternative to wandb
      
      # Configuration
      - omegaconf>=2.3.0
      - hydra-core>=1.3.0
      - typer>=0.9.0
      - pydantic>=2.3.0
      - rich>=13.5.0
      
      # Additional visualization
      - plotly-bio>=1.0.0
      - nglview>=3.0.0  # For 3D molecular visualization
      
      # Specialized tools
      - scanpy>=1.9.0  # For single-cell style analysis
      - anndata>=0.9.0  # Annotated data format

# Environment variables
variables:
  CUDA_HOME: /usr/local/cuda-11.8
  TORCH_CUDA_ARCH_LIST: "7.0;7.5;8.0;8.6"